"""Set up MCP servers for Claude Code and OpenCode in one shot."""

import shlex
import shutil
import subprocess
from pathlib import Path

import rich_click as click
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from evo_cli.commands.opencode import (
    get_global_config_path,
    load_jsonc,
    save_jsonc,
)
from evo_cli.console import console, error, info, run_command, step, success, warning
from evo_cli.mcp_registry import MCP_REGISTRY, is_remote, to_opencode_config

EPILOG = Text.from_markup(
    "[bold]Examples[/bold]\n\n"
    "  [cyan]evo mcp list[/cyan]\n"
    "  [cyan]evo mcp add playwright[/cyan]\n"
    "  [cyan]evo mcp add notion --claude-only[/cyan]\n"
    "  [cyan]evo mcp add notion --opencode-only --project .[/cyan]\n"
    "  [cyan]evo mcp add my-remote --url https://example.com/mcp --transport http[/cyan]\n"
    '  [cyan]evo mcp add my-local --command "npx -y some-mcp" --env API_KEY=xxx[/cyan]'
)


def claude_has_server(name):
    result = subprocess.run(
        ["claude", "mcp", "get", name],
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def add_to_claude(name, spec, scope, force=False):
    step("Adding to Claude Code")
    if not shutil.which("claude"):
        warning("`claude` CLI not found on PATH; skipping Claude Code")
        info("Install Claude Code, then re-run to register this MCP server")
        return False

    if claude_has_server(name):
        if not force:
            info(f"MCP server [accent]{name}[/accent] already in Claude Code; skipping")
            return True
        info(f"Replacing existing [accent]{name}[/accent] in Claude Code")
        run_command(["claude", "mcp", "remove", "--scope", scope, name], check=False)

    cmd = ["claude", "mcp", "add", "--scope", scope]
    if is_remote(spec):
        cmd += ["--transport", spec["transport"], name, spec["url"]]
    else:
        # `claude mcp add` declares -e as variadic (`-e <env...>`), so any flag placed
        # before the positional name swallows it as another KEY=value and the command
        # dies with "Invalid environment variable format: <name>". Name first.
        cmd += [name]
        for key, value in (spec.get("env") or {}).items():
            cmd += ["-e", f"{key}={value}"]
        cmd += ["--", *spec["command"]]
    if spec.get("headers"):
        for key, value in spec["headers"].items():
            cmd += ["--header", f"{key}: {value}"]

    try:
        run_command(cmd)
    except Exception as exc:
        error(f"Could not add to Claude Code: {exc}")
        return False
    success(f"Added [accent]{name}[/accent] to Claude Code ({scope} scope)")
    info("Run /mcp inside Claude Code to authenticate if the server needs OAuth")
    return True


def add_to_opencode(name, spec, project, force=False):
    step("Adding to OpenCode")
    server_config = to_opencode_config(spec)

    config_path = get_global_config_path()
    existing = load_jsonc(config_path) if config_path.exists() else {}
    mcp = existing.setdefault("mcp", {})
    if name in mcp and not force:
        info(f"MCP server [accent]{name}[/accent] already in OpenCode global; skipping")
    elif name in mcp and mcp[name] == server_config:
        info(f"MCP server [accent]{name}[/accent] already matches in OpenCode global; unchanged")
    else:
        replacing = name in mcp
        mcp[name] = server_config
        header = "// OpenCode global configuration generated by evo"
        save_jsonc(config_path, existing, header=header)
        verb = "Replaced" if replacing else "Added"
        success(f"{verb} [accent]{name}[/accent] in OpenCode global config")
    info(f"Config: [accent]{config_path}[/accent]")

    if project:
        target = Path(project).resolve()
        proj_path = target / "opencode.json"
        proj_existing = load_jsonc(proj_path) if proj_path.exists() else {}
        proj_mcp = proj_existing.setdefault("mcp", {})
        if name in proj_mcp and not force:
            info(f"MCP server [accent]{name}[/accent] already in project config; skipping")
        else:
            proj_mcp[name] = server_config
            header = "// OpenCode project configuration generated by evo"
            save_jsonc(proj_path, proj_existing, header=header)
            success(f"Added [accent]{name}[/accent] to project config [accent]{proj_path}[/accent]")
    return True


def resolve_spec(name, url, transport, command=None, env=None):
    if url and command:
        raise click.BadParameter("Use either --url (remote) or --command (local), not both.")
    if url:
        if transport not in ("http", "sse"):
            raise click.BadParameter("--transport must be http or sse when using --url")
        return {"transport": transport, "url": url, "description": "custom remote server"}
    if command:
        argv = shlex.split(command) if isinstance(command, str) else list(command)
        if not argv:
            raise click.BadParameter("--command must contain a command to run.")
        spec = {"transport": "stdio", "command": argv, "description": "custom local server"}
        if env:
            spec["env"] = dict(env)
        return spec
    if name in MCP_REGISTRY:
        return MCP_REGISTRY[name]
    raise click.BadParameter(
        f"Unknown MCP server '{name}'. Run `evo mcp list` to see the catalog, "
        "or pass --url (remote) / --command (local) to add a custom one."
    )


@click.group("mcp", help="Set up MCP servers for Claude Code and OpenCode.")
def mcp_group():
    """Register MCP servers across your AI coding tools at once."""


@mcp_group.command("list")
def list_servers():
    """List the MCP servers in the curated library."""
    table = Table(title="MCP server library", title_style="step", expand=False)
    table.add_column("Name", style="accent")
    table.add_column("Category", style="info")
    table.add_column("Type", style="info")
    table.add_column("Endpoint / command", style="dim", overflow="fold")
    table.add_column("Description")
    for name, spec in MCP_REGISTRY.items():
        endpoint = spec.get("url") or " ".join(spec.get("command", []))
        kind = "remote" if is_remote(spec) else "local"
        table.add_row(name, spec.get("category", "-"), kind, endpoint, spec["description"])
    console.print(table)
    console.print(
        "\nAdd one with [accent]evo mcp add <name>[/accent], a custom remote with "
        '[accent]--url <url>[/accent], or a custom local with [accent]--command "<cmd>"[/accent].'
    )


@mcp_group.command("add", epilog=EPILOG)
@click.argument("name")
@click.option("--url", help="Custom remote MCP endpoint (for servers not in the library).")
@click.option(
    "--command",
    help='Custom local (stdio) MCP server command, e.g. "npx -y some-mcp".',
)
@click.option(
    "--env",
    "env",
    multiple=True,
    metavar="KEY=VALUE",
    help="Environment variable for a custom --command server (repeatable).",
)
@click.option(
    "--transport",
    type=click.Choice(["http", "sse"]),
    default="http",
    show_default=True,
    help="Transport for a custom --url server.",
)
@click.option(
    "--scope",
    type=click.Choice(["local", "user", "project"]),
    default="user",
    show_default=True,
    help="Claude Code config scope.",
)
@click.option("--claude-only", is_flag=True, help="Only configure Claude Code.")
@click.option("--opencode-only", is_flag=True, help="Only configure OpenCode.")
@click.option(
    "--force",
    is_flag=True,
    help="Replace an existing entry instead of leaving it alone (use when --env or the command changed).",
)
@click.option(
    "--project",
    type=click.Path(file_okay=False, dir_okay=True),
    help="Also write into a project-level opencode.json at this directory.",
)
def add_server(name, url, command, env, transport, scope, claude_only, opencode_only, force, project):
    """Add an MCP server to Claude Code and OpenCode.

    NAME is a key from the library (`evo mcp list`), or any label when paired
    with --url (custom remote server) or --command (custom local server). By
    default the server is registered in both tools; use --claude-only or
    --opencode-only to limit the scope.

    Remote servers that use OAuth (like notion) prompt for sign-in on first use:
    run /mcp inside Claude Code, and OpenCode triggers the flow on next launch.
    """
    if claude_only and opencode_only:
        error("--claude-only and --opencode-only are mutually exclusive")
        return

    env_map = {}
    for item in env:
        if "=" not in item:
            error(f"Invalid --env '{item}'; expected KEY=VALUE")
            return
        key, value = item.split("=", 1)
        env_map[key] = value

    try:
        spec = resolve_spec(name, url, transport, command, env_map or None)
    except click.BadParameter as exc:
        error(str(exc))
        return

    step(f"evo mcp add {name}")
    info(spec.get("description", "custom"))

    did_claude = did_opencode = False
    if not opencode_only:
        did_claude = add_to_claude(name, spec, scope, force=force)
    if not claude_only:
        did_opencode = add_to_opencode(name, spec, project, force=force)

    console.print()
    targets = []
    if did_claude:
        targets.append("Claude Code")
    if did_opencode:
        targets.append("OpenCode")
    summary = ", ".join(targets) if targets else "no tools (check warnings above)"
    console.print(
        Panel(
            f"MCP server [accent]{name}[/accent] configured for: {summary}.\n\n"
            "Restart OpenCode and authenticate in Claude Code (/mcp) if prompted.",
            title="mcp add complete",
            border_style="success",
            expand=False,
        )
    )
