"""Set up MCP servers for Claude Code and OpenCode in one shot."""

import shutil
import subprocess
from pathlib import Path

import rich_click as click
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from evo_cli.commands.opencode import (
    get_global_config_path,
    load_jsonc,
    save_jsonc,
)
from evo_cli.console import console, error, info, run_command, step, success, warning

EPILOG = Text.from_markup(
    "[bold]Examples[/bold]\n\n"
    "  [cyan]evo mcp list[/cyan]\n"
    "  [cyan]evo mcp add notion[/cyan]\n"
    "  [cyan]evo mcp add notion --claude-only[/cyan]\n"
    "  [cyan]evo mcp add notion --opencode-only --project .[/cyan]\n"
    "  [cyan]evo mcp add my-server --url https://example.com/mcp --transport http[/cyan]"
)

MCP_REGISTRY = {
    "notion": {
        "transport": "http",
        "url": "https://mcp.notion.com/mcp",
        "description": "Notion workspace - pages, databases, search. OAuth on first use.",
    },
    "context7": {
        "transport": "http",
        "url": "https://mcp.context7.com/mcp",
        "description": "Context7 - up-to-date library docs and code examples.",
    },
    "deepwiki": {
        "transport": "sse",
        "url": "https://mcp.deepwiki.com/sse",
        "description": "DeepWiki - ask questions about any public GitHub repo.",
    },
}


def to_opencode_config(spec):
    if spec["transport"] in ("http", "sse"):
        config = {"type": "remote", "url": spec["url"], "enabled": True}
        if spec.get("headers"):
            config["headers"] = dict(spec["headers"])
        return config
    config = {"type": "local", "command": list(spec["command"]), "enabled": True}
    if spec.get("env"):
        config["environment"] = dict(spec["env"])
    return config


def claude_has_server(name):
    result = subprocess.run(
        ["claude", "mcp", "get", name],
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def add_to_claude(name, spec, scope):
    step("Adding to Claude Code")
    if not shutil.which("claude"):
        warning("`claude` CLI not found on PATH; skipping Claude Code")
        info("Install Claude Code, then re-run to register this MCP server")
        return False

    if claude_has_server(name):
        info(f"MCP server [accent]{name}[/accent] already in Claude Code; skipping")
        return True

    cmd = ["claude", "mcp", "add", "--scope", scope]
    if spec["transport"] in ("http", "sse"):
        cmd += ["--transport", spec["transport"], name, spec["url"]]
    else:
        for key, value in (spec.get("env") or {}).items():
            cmd += ["-e", f"{key}={value}"]
        cmd += [name, "--", *spec["command"]]
    if spec.get("headers"):
        for key, value in spec["headers"].items():
            cmd += ["--header", f"{key}: {value}"]

    try:
        run_command(cmd)
    except Exception as exc:
        error(f"Could not add to Claude Code: {exc}")
        return False
    success(f"Added [accent]{name}[/accent] to Claude Code ({scope} scope)")
    info("Run /mcp inside Claude Code to authenticate if the server needs OAuth")
    return True


def add_to_opencode(name, spec, project):
    step("Adding to OpenCode")
    server_config = to_opencode_config(spec)

    config_path = get_global_config_path()
    existing = load_jsonc(config_path) if config_path.exists() else {}
    mcp = existing.setdefault("mcp", {})
    if name in mcp:
        info(f"MCP server [accent]{name}[/accent] already in OpenCode global; skipping")
    else:
        mcp[name] = server_config
        header = "// OpenCode global configuration generated by evo"
        save_jsonc(config_path, existing, header=header)
        success(f"Added [accent]{name}[/accent] to OpenCode global config")
    info(f"Config: [accent]{config_path}[/accent]")

    if project:
        target = Path(project).resolve()
        proj_path = target / "opencode.json"
        proj_existing = load_jsonc(proj_path) if proj_path.exists() else {}
        proj_mcp = proj_existing.setdefault("mcp", {})
        if name in proj_mcp:
            info(f"MCP server [accent]{name}[/accent] already in project config; skipping")
        else:
            proj_mcp[name] = server_config
            header = "// OpenCode project configuration generated by evo"
            save_jsonc(proj_path, proj_existing, header=header)
            success(f"Added [accent]{name}[/accent] to project config [accent]{proj_path}[/accent]")
    return True


def resolve_spec(name, url, transport):
    if url:
        if transport not in ("http", "sse"):
            raise click.BadParameter("--transport must be http or sse when using --url")
        return {"transport": transport, "url": url, "description": "custom"}
    if name in MCP_REGISTRY:
        return MCP_REGISTRY[name]
    raise click.BadParameter(
        f"Unknown MCP server '{name}'. Run `evo mcp list` to see known servers, or pass --url to add a custom one."
    )


@click.group("mcp", help="Set up MCP servers for Claude Code and OpenCode.")
def mcp_group():
    """Register MCP servers across your AI coding tools at once."""


@mcp_group.command("list")
def list_servers():
    """List the MCP servers bundled in the registry."""
    table = Table(title="Known MCP servers", title_style="step", expand=False)
    table.add_column("Name", style="accent")
    table.add_column("Transport", style="info")
    table.add_column("Endpoint", style="dim")
    table.add_column("Description")
    for name, spec in MCP_REGISTRY.items():
        endpoint = spec.get("url") or " ".join(spec.get("command", []))
        table.add_row(name, spec["transport"], endpoint, spec["description"])
    console.print(table)
    console.print(
        "\nAdd one with [accent]evo mcp add <name>[/accent], "
        "or a custom server with [accent]evo mcp add <name> --url <url>[/accent]."
    )


@mcp_group.command("add", epilog=EPILOG)
@click.argument("name")
@click.option("--url", help="Custom remote MCP endpoint (for servers not in the registry).")
@click.option(
    "--transport",
    type=click.Choice(["http", "sse"]),
    default="http",
    show_default=True,
    help="Transport for a custom --url server.",
)
@click.option(
    "--scope",
    type=click.Choice(["local", "user", "project"]),
    default="user",
    show_default=True,
    help="Claude Code config scope.",
)
@click.option("--claude-only", is_flag=True, help="Only configure Claude Code.")
@click.option("--opencode-only", is_flag=True, help="Only configure OpenCode.")
@click.option(
    "--project",
    type=click.Path(file_okay=False, dir_okay=True),
    help="Also write into a project-level opencode.json at this directory.",
)
def add_server(name, url, transport, scope, claude_only, opencode_only, project):
    """Add an MCP server to Claude Code and OpenCode.

    NAME is a key from the registry (`evo mcp list`) or any label when paired
    with --url for a custom remote server. By default the server is registered
    in both tools; use --claude-only or --opencode-only to limit the scope.

    Remote servers that use OAuth (like notion) prompt for sign-in on first use:
    run /mcp inside Claude Code, and OpenCode triggers the flow on next launch.
    """
    if claude_only and opencode_only:
        error("--claude-only and --opencode-only are mutually exclusive")
        return

    try:
        spec = resolve_spec(name, url, transport)
    except click.BadParameter as exc:
        error(str(exc))
        return

    step(f"evo mcp add {name}")
    info(spec.get("description", "custom"))

    did_claude = did_opencode = False
    if not opencode_only:
        did_claude = add_to_claude(name, spec, scope)
    if not claude_only:
        did_opencode = add_to_opencode(name, spec, project)

    console.print()
    targets = []
    if did_claude:
        targets.append("Claude Code")
    if did_opencode:
        targets.append("OpenCode")
    summary = ", ".join(targets) if targets else "no tools (check warnings above)"
    console.print(
        Panel(
            f"MCP server [accent]{name}[/accent] configured for: {summary}.\n\n"
            "Restart OpenCode and authenticate in Claude Code (/mcp) if prompted.",
            title="mcp add complete",
            border_style="success",
            expand=False,
        )
    )
